# WARNING - Generated by {fusen} from dev/flat_simulate_env.Rmd: do not edit by hand

test_that("generate_env_layer works", {

  grid <- create_grid()
  output <- generate_env_layer(norm = FALSE, return.rasters = FALSE, grid = grid)

  expect_true(inherits(output, "data.frame"))

  expect_true(length(generate_env_layer(grid = grid)) == 2)
})
