# WARNING - Generated by {fusen} from dev/flat_simulate_survey.Rmd: do not edit by hand

test_that("assign_flight_plan works", {
  
  surv <- generate_survey_plan(bbx_xmin = 5, bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 5, end_x = 85, start_y = 5, end_y = 85,
                             space_out_factor = 4, segmentize = TRUE, seg_length = 1, 
                             buffer = TRUE, buffer_width = 0.2
                             )

  flight_id <- c(1:80, 160:81, 161:240, 320:241, 321:400, 480:401, 481:560, 640:561, 641:720, 800:721, 801:880, 960:881, 961:1040,
                   1120:1041, 1121:1200, 1280:1201, 1281:1360, 1440:1361, 1441:1520, 1600:1521, 1601:1680)

  expect_error(
    object = assign_flight_plan(
    sf_segments = surv$buffered_segments,
    flight_id = flight_id,
    col_trans_id = "toto",
    flight_day = "2022-02-08", 
    survey_start_hour = "06:00:00",
    flight_speed = 160,
    intertransect_gap_duration = 60),
    regexp = "col_trans_id must be a column of sf_segments"
  )
  
  expect_error(
    object = assign_flight_plan(
    sf_segments = surv$buffered_segments,
    flight_id = flight_id,
    col_trans_id = "transect",
    flight_day = 2022, 
    survey_start_hour = "06:00:00",
    flight_speed = 160,
    intertransect_gap_duration = 60),
    regexp = "flight_day, survey_start_hour and col_trans_id must be character"
  )
  
  expect_error(
    object = assign_flight_plan(
    sf_segments = surv$segments,
    flight_id = flight_id,
    col_trans_id = "transect",
    flight_day = "2022-02-08", 
    survey_start_hour = "06:00:00",
    flight_speed = 160,
    intertransect_gap_duration = 60),
    regexp = "sf_segments geometry is not of type POLYGON"
  )
})

