# WARNING - Generated by {fusen} from dev/flat_simulate_sp.Rmd: do not edit by hand

test_that("simul_spat works", {
  grid <- create_grid()
  cdt <- generate_env_layer(grid = grid)
  rsce <- generate_resource_layer(env_layers = cdt$rasters,
                              beta = c(2, -1.5))
  
  # expect_warning(
  #     object = simul_spat(ref_map = rsce$rasters, n_sim = 2, return_wgs_coordinates = FALSE, N = 1000, mean_group_size = 10),
  #     regexp = "ref_map has no crs, is that voluntary? The output will have no crs."
  #   )
    
    expect_error(
      object = simul_spat(ref_map = rsce$rasters, n_sim = 2, return_wgs_coordinates = TRUE, N = 1000, mean_group_size = 10)
    )

})
