# WARNING - Generated by {fusen} from dev/flat_simulate_survey.Rmd: do not edit by hand

test_that("detection_process works", {
  grid <- create_grid()
  env <- generate_env_layer(grid = grid)
  sp <- suppressWarnings(simul_spat(ref_map = env$rasters$sim1,N = 1000, n_sim = 1, return_wgs_coordinates = F))
  surv <- generate_survey_plan(bbx_xmin = 5, bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 10, end_x = 80, start_y = 10, end_y = 80,
                             space_out_factor = 4, segmentize = TRUE, seg_length = 2, 
                             buffer = TRUE, buffer_width = 0.2
                             )
  
  expect_error(
    object = detection_process(pts = sp, 
                         transects = surv$segments, 
                         strip_transect = TRUE, 
                         sigma = 0.2, 
                         virtual_space = TRUE),
    regexp = "seg_id_col must be provided")
  
  expect_error(
    object = detection_process(pts = "sp", 
                         transects = surv$segments, 
                         strip_transect = TRUE, 
                         sigma = 0.2, 
                         virtual_space = TRUE),
    regexp = "pts and transects must be sf objects")
  
  expect_error(
    object = detection_process(pts = sp, 
                         transects = sp, 
                         strip_transect = TRUE, 
                         sigma = 0.2, 
                         virtual_space = TRUE),
    regexp = "transects geometry is not of type LINESTRING")
} )
