# WARNING - Generated by {fusen} from dev/flat_simulate_survey.Rmd: do not edit by hand

test_that("launch_survey_on_movement works", {
  # test we get errors when survey data are not sf objects
  expect_error(
    object = launch_survey_on_movement(
                survey_data_buffered = "example_data",
                survey_data_linear = example_data$survey$segments[840:860,],
                traj_data = example_data$mvmt_data,
                line_transect = TRUE, detection_function = "hn",
                sigma = 0.2
              )
    ,regexp = "survey_data_buffered and survey_data_linear must be a sf object"
  )
  expect_error(
    object = launch_survey_on_movement(
                survey_data_buffered = example_data$survey$buffered_segments[840:860,],
                survey_data_linear = "example_data$survey$segments[840:860,]",
                traj_data = example_data$mvmt_data,
                line_transect = TRUE, detection_function = "hn",
                sigma = 0.2
              )
    ,regexp = "survey_data_buffered and survey_data_linear must be a sf object"
  )
  # test we get an error when traj_data is an sf object
  expect_error(
    object = launch_survey_on_movement(
                survey_data_buffered = example_data$survey$buffered_segments[840:860,],
                survey_data_linear = example_data$survey$segments[840:860,],
                traj_data = example_data$survey$segments[840:860,],
                line_transect = TRUE, detection_function = "hn",
                sigma = 0.2
              )
    ,regexp = "traj_data must be a data.frame"
  )
})
