# WARNING - Generated by {fusen} from dev/flat_simulate_survey.Rmd: do not edit by hand

test_that("generate_survey_plan works", {
  
  expect_error(
    object = generate_survey_plan(bbx_xmin = 5, bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 10, end_x = 80, start_y = 10, end_y = 80,
                             space_out_factor = 4, segmentize = TRUE, seg_length = "b",
                             buffer = TRUE, buffer_width = 0.2
                             ),
    regexp = "seg_length must be numeric"
  )
  
  expect_error(
    object = generate_survey_plan(bbx_xmin = 5, bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 10, end_x = 80, start_y = 10, end_y = 80,
                             space_out_factor = 4, segmentize = TRUE, seg_length = 2,
                             buffer = TRUE, buffer_width = "b"
                             ),
    regexp = "buffer_width must be numeric"
  )
  
  expect_error(
    object = generate_survey_plan(bbx_xmin = 5, bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 10, end_x = 80, start_y = 10, end_y = 80,
                             space_out_factor = 4, segmentize = TRUE, seg_length = 2,
                             buffer = "TRUE", buffer_width = 2
                             ),
    regexp = "buffer must be Boolean"
  )
  
  expect_error(
    object = generate_survey_plan(bbx_xmin = 5, bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 10, end_x = 80, start_y = 10, end_y = 80,
                             space_out_factor = 4, segmentize = "TRUE", seg_length = 2,
                             buffer = TRUE, buffer_width = 2
                             ),
    regexp = "segmentize must be Boolean"
  )
  
  expect_error(
    object = generate_survey_plan(bbx_xmin = "5", bbx_xmax = 85, bbx_ymin = 5, bbx_ymax = 85,
                             start_x = 10, end_x = 80, start_y = 10, end_y = 80,
                             space_out_factor = 4, segmentize = TRUE, seg_length = 2,
                             buffer = TRUE, buffer_width = 2
                             ),
    regexp = "bbx_xmin, bbx_xmax, bbx_ymin, bbx_ymax, start_x, end_x, start_y, end_y, space_out_factor must all be numeric"
  )
})
