# WARNING - Generated by {fusen} from dev/flat_simulate_survey.Rmd: do not edit by hand

test_that("assign_flight_plan works", {
  
  surv <- generate_survey_plan(bbx_xmin = 30, bbx_xmax = 65, bbx_ymin = 30, bbx_ymax = 65,
                             start_x = 34, end_x = 60, start_y = 34, end_y = 68,
                             space_out_factor = 2, segmentize = TRUE, seg_length = 1,
                             buffer = TRUE, buffer_width = 0.2
  )

  expect_error(
    object = assign_flight_plan(
    sf_segments = surv$buffered_segments,
    flight_id =  c(1:468),
    col_trans_id = "toto",
    flight_day = "2022-02-08", 
    survey_start_hour = "06:00:00",
    flight_speed = 160,
    intertransect_gap_duration = 60),
    regexp = "col_trans_id must be a column of sf_segments"
  )
  
  expect_error(
    object = assign_flight_plan(
    sf_segments = surv$buffered_segments,
    flight_id =  c(1:468),
    col_trans_id = "transect",
    flight_day = 2022, 
    survey_start_hour = "06:00:00",
    flight_speed = 160,
    intertransect_gap_duration = 60),
    regexp = "flight_day, survey_start_hour and col_trans_id must be character"
  )
  
  expect_error(
    object = assign_flight_plan(
    sf_segments = surv$segments,
    flight_id =  c(1:468),
    col_trans_id = "transect",
    flight_day = "2022-02-08", 
    survey_start_hour = "06:00:00",
    flight_speed = 160,
    intertransect_gap_duration = 60),
    regexp = "sf_segments geometry is not of type POLYGON"
  )
})

