# WARNING - Generated by {fusen} from dev/flat_simulate_mvmt.Rmd: do not edit by hand

test_that("potential_position_func works", {
  expect_true(inherits(potential_position_func, "function")) 
  
  from <- data.frame(Lon = 1, Lat = 2, toto = 5)
  colony_location <- data.frame(Lon = 2, Lat = 5)
  cdt <- generate_env_layer(grid = create_grid(), n = 1)$rasters

  # check returns an error if env_rast is not a raster
  expect_error(
    object = potential_position_func(from = from, 
                                     colony_location = colony_location, resource_layer = from)
  )
  # check returns an error if from does not include coord_col names
  expect_error(
    object = potential_position_func(from = from[,c("Lon","toto")], 
                                     colony_location = colony_location, resource_layer = cdt)
  )
  # check returns an error when bearing is not of length 2
  expect_error(
    object = potential_position_func(from = from, coord_col = coord_col,
                                     colony_location = colony_location, resource_layer = cdt,
                                     bearing = 1, step = c(2,3))
  )
})
