# WARNING - Generated by {fusen} from dev/flat_simulate_env.Rmd: do not edit by hand

test_that("create_grid works", {
  expect_true(inherits(create_grid, "function")) 
  expect_true(inherits(create_grid(), "data.frame")) 
})
