# WARNING - Generated by {fusen} from dev/flat_simulate_env.Rmd: do not edit by hand

#' Create the grid of a virtual environment
#'
#' @param ymin Minimum latitude (default to 0)
#' @param ymax Maximum latitude (default to 90)
#' @param xmin Minimum longitude (default to 0)
#' @param xmax Maximum latitude (default to 90)
#' @param step_x Longitude steps to be used to generate points (default to 0.5)
#' @param step_y Latitude steps to be used to generate points (default to 0.5)
#'
#' @return A grid in dataframe format. 
#' @export
#'
#' @examples
#' grid <- create_grid()
create_grid <- function(ymin = 0, ymax = 90, xmin = 0, xmax = 90, step_x = 0.5, step_y = 0.5){
  xy <- expand.grid(seq(xmin, xmax, step_x), seq(xmin, ymax, step_y))
  colnames(xy) <- c("x","y")
  return(xy)
}
