# WARNING - Generated by {fusen} from dev/flat_simulate_env.Rmd: do not edit by hand


#' Not in
#'
#' @param x,y Numeric vectors
#' 
#' @return Boolean
#' @export
#'
'%!in%' <- function(x,y)!('%in%'(x,y))

#' Normalize a vector
#'
#' @param cov a vector
#' 
#' @return a vector
#' @export
normalize <- function(cov){ (cov-min(cov))/(max(cov)-min(cov)) }
# normalize <- function(cov){ cov/max(cov) }



#' Create the grid of a virtual environment
#'
#' @param ymin Minimum latitude (default to 0)
#' @param ymax Maximum latitude (default to 90)
#' @param xmin Minimum longitude (default to 0)
#' @param xmax Maximum latitude (default to 90)
#' @param step.x Longitude steps to be used to generate points (default to 0.5)
#' @param step.y Latitude steps to be used to generate points (default to 0.5)
#'
#' @return A grid in dataframe format. 
#' @export
#'
#' @examples
#' grid <- create_grid()
create_grid <- function(ymin = 0, ymax = 90, xmin = 0, xmax = 90, step.x = 0.5, step.y = 0.5){
  xy <- expand.grid(seq(xmin, xmax, step.x), seq(xmin, ymax, step.y))
  colnames(xy) <- c("x","y")
  return(xy)
}
