# WARNING - Generated by {fusen} from dev/flat_simulate_survey.Rmd: do not edit by hand

#' Half-normal detection function
#' 
#' @export
#' @rdname detection_functions
detfunc_hn <- function(x, sigma) {return(exp(-((x/sigma)^2)/2))}

#' Hazard rate detection function
#' 
#' @export
#' @rdname detection_functions
detfunc_hr <- function(x, sigma, b) {return( 1-exp(-(x/sigma)^(-b)) )}

