# WARNING - Generated by {fusen} from dev/flat_simulate_env.Rmd: do not edit by hand

#' Generating random environmental layers
#'
#' @param seed Value to feed set.seed (default 2)
#' @param grid Grid of the virtual space, as generated by create_grid()
#' @param n Number of layers to be generated (default 2)
#' @param beta The beta value to be forwarded to gstat (default to 1)
#' @param norm Should the resulting layers be normalized? 
#' @param return.rasters Should the function returns SpatRast in addition to data frame?
#'
#' @return Returns a data frame with the simulated environmental values, as well as SpatRast is return.rasters = TRUE
#' @export
#' 
#' @importFrom gstat gstat
#' @importFrom gstat vgm
#' @importFrom terra rast
#' @importFrom stats predict
#' 
#' @examples
#' grid <- create_grid()
#'
#' str(generate_env_layer(norm = FALSE, return.rasters = FALSE, grid = grid))
#' str(generate_env_layer(norm = TRUE, return.rasters = FALSE, grid = grid))
#'
#' library(terra)
#' plot(generate_env_layer(norm = TRUE, return.rasters = TRUE, grid = grid)$rasters)
#' plot(generate_env_layer(norm = FALSE, return.rasters = TRUE, grid = grid)$rasters)
generate_env_layer <- function(seed = 2, 
                               grid, 
                               n = 2, 
                               beta = 1, 
                               norm = TRUE, 
                               return.rasters = TRUE){
  set.seed(seed)
  field <- gstat::gstat(formula = z~1, locations = ~x+y, dummy = TRUE, beta = beta, 
                 model = gstat::vgm(psill = 100, range = 100, model = 'Exp'), nmax = 20)
  cov <- predict(field, newdata = grid, nsim = n)
  
  if(norm == TRUE){
    for(i in 1:n){
      cov[,2+i] <- normalize(cov[, 2+i])
    }
    if(return.rasters == TRUE){
      rast.stack <- terra::rast(x = cov, type = "xyz")
      return(list(dataframe = cov, rasters = rast.stack))
    } else {
      return(cov)
    }
  } else {
    if(return.rasters == TRUE){
      rast.stack <- terra::rast(x = cov, type = "xyz")
      return(list(dataframe = cov, rasters = rast.stack))
    } else {
      return(cov)
    }
  }
}

