# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Launch help for the package
#'
#' @importFrom utils browseURL
#' @return the website
#' @export
#'
#' @examples
#' launch_help()
launch_help <- function(){
  system.file("site", "index.html", package = "simtools") |>
    utils::browseURL()
}
