# WARNING - Generated by {fusen} from dev/flat_simulate_mvmt.Rmd: do not edit by hand

#' Return random direction angles
#'
#' @inheritParams circular::rwrappednormal 
#'
#' @importFrom circular rwrappednormal 
#'
#' @return
#' @export
#'
randomdir <- function(n,mu,kappa){
  out <- circular::rwrappednormal(10, mu = circular::circular(mu, units = "degrees", 
                                                              template = "geographic"),
                                 sd = kappa, control.circular = list()) %% 360
  return(as.double(out))
}

#' Return random step lengths
#'
#' @inheritParams stats::rgamma 
#'
#' @importFrom stats rgamma 
#'
#' @return
#' @export
#'
#' @examples
randomdist <- function(n, shape, rate){
  out <- stats::rgamma(n, shape, rate)
  return(out)
}
