# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Not in
#'
#' @param x,y Numeric vectors
#' 
#' @return Boolean
#' @export
#'
#' @examples
#' 1 %!in% c(2:3)
#'
#' 2 %!in% c(2:3)
'%!in%' <- function(x,y){!('%in%'(x,y))}
